### ISSUE TITLE
AUR build error

### ISSUE THREAD

**Issue by kaboussi** [kaboussi/Botflix#48]
#47 @aurkaxi

**Comment by aurkaxi** [comment]
I updated the PKGBUILD, can you check again?
```bash
if ! yay -Qi webtorrent-cli &> /dev/null && ! npm list -g webtorrent-cli &> /dev/null; then
  echo "Installing webtorrent-cli"
  yay -S --noconfirm --needed webtorrent-cli
fi
```

**Comment by kaboussi** [comment]
Yes, it works now, thanks in advance.

**Comment by tralph3** [comment]
This is not the proper way to do things. Simply add `webtorrent-cli` to the list of dependencies. Using yay in the PKGBUILD forces everyone to have yay to build the package.

Users of other AUR helpers, or even worse, users that do not use AUR helpers at all **since they are not officially supported** can't build this package.

Please, scratch this.

**Comment by aurkaxi** [comment]
`webtorrent-cli` is from aur. We can't add aur package as dependency, can we?

**Comment by tralph3** [comment]
You can.

**Comment by aurkaxi** [comment]
```
❯ makepkg -si
==> Making package: botflix-git r158.a75cbd5-1 (Sun 09 Jun 2024 12:50:01 AM +06)
==> Checking runtime dependencies...
==> Installing missing dependencies...
[sudo] password for aurka:        
error: target not found: webtorrent-cli
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> npm
  -> webtorrent-cli
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

I don't think so.

**Comment by tralph3** [comment]
It worked. It correctly detected you are missing a dependency. Now you can install it, instead of forcing me to use a specific AUR helper.
